name: cellenone_env
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=7.0.1=pyha191276_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.2=pyh0d26453_1
  - psutil=7.1.0=py314h5bd0f2a_0
  - python=3.14.0=h3fc5862_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python_abi=3.14=1_cp314
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lance-namespace==0.0.21
      - lance-namespace-urllib3-client==0.0.21
      - lightning==2.5.6
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pylance==0.39.0
      - pyparsing==3.2.5
      - pytorch-lightning==2.5.6
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.16.2
      - seaborn==0.13.2
      - sentry-sdk==2.46.0
      - setuptools==80.9.0
      - smmap==5.0.2
      - sympy==1.14.0
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.23.0
      - yarl==1.22.0
