name: cellenone_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py314h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - comm=0.2.3=py314h06a4308_0
  - cpython=3.14.0=py314hd8ed1ab_102
  - debugpy=1.8.16=py314hbdd6827_1
  - decorator=5.2.1=py314h06a4308_0
  - executing=2.2.1=py314h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ipykernel=7.0.1=pyha191276_0
  - ipython=9.7.0=py314h06a4308_0
  - ipython_pygments_lexers=1.1.1=py314h06a4308_0
  - jedi=0.19.2=py314h06a4308_0
  - jupyter_client=8.6.3=py314h06a4308_1
  - jupyter_core=5.8.1=py314h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libmpdec=4.0.0=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=py314h06a4308_0
  - pexpect=4.9.0=py314h06a4308_1
  - pip=25.2=pyh0d26453_1
  - platformdirs=4.5.0=py314h06a4308_0
  - prompt-toolkit=3.0.52=py314h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.1.0=py314h5bd0f2a_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py314h06a4308_0
  - pygments=2.19.2=py314h06a4308_0
  - python=3.14.0=h3fc5862_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python_abi=3.14=1_cp314
  - pyzmq=27.1.0=py314hcf8288c_1
  - readline=8.3=hc2a1206_0
  - six=1.17.0=py314h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py314h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py314h5eee18b_0
  - traitlets=5.14.3=py314h06a4308_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.13=py314h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - cellpose==4.0.7
      - cellvisionpkg==0.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - fastremap==1.17.7
      - filelock==3.20.0
      - fill-voids==2.1.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - imagecodecs==2025.11.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lance-namespace==0.0.21
      - lance-namespace-urllib3-client==0.0.21
      - lazy-loader==0.4
      - lightning==2.5.6
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - natsort==8.4.0
      - networkx==3.5
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pylance==0.39.0
      - pyparsing==3.2.5
      - pytorch-lightning==2.5.6
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - roifile==2025.5.10
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - segment-anything==1.0
      - sentry-sdk==2.46.0
      - setuptools==80.9.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.23.0
      - yarl==1.22.0
